name: CI devops 2024

on:
  # Launch the CI pipeline on pushes to the main and develop branches
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      # Set up JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and test the application with Maven
      - name: Build and test with Maven
        run: 
          cd simple-api && mvn clean verify
